# == Global project settings ===========================================

name:             Open Terrain
description:      ''
attribution:      ''
center:           [-121.7615, 46.8733, 9]
format:           png8
interactivity:    false
minzoom:          8
maxzoom:          20
srs:              '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'
metatile:         1


# == Layer & Datasource defaults =======================================

_layer_default:   &layer
  'srs-name':     '3857'
  srs:            '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'

# == Stylesheets =======================================================

Stylesheet:
  - style.mss

# == Layers ============================================================

Layer:

  - <<: *layer
    name: hillshade
    id:   hillshade
    geometry: raster
    extent: [-179.9999993623526, -60.00005655617617, 179.9983250186893, 60.00041727199608]
    properties:
      minzoom: 8
    Datasource:
      file: SRTM-hillshade-3857-local.vrt
